---
app_config:
  backend:
    repo: https://github.com/william-prof/pratica-backend.git
    branch: dev
    container_name: pratica-backend
  frontend:
    repo: https://github.com/william-prof/pratica-frontend.git
    branch: dev
    container_name: pratica-frontend
